/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RhNewsRouteImport } from './routes/rh-news'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as RsIndexRouteImport } from './routes/rs.index'
import { Route as RsIdRouteImport } from './routes/rs.$id'
import { Route as RsPainelRouteImport } from './routes/rs.painel'
import { Route as ApiPublicNewsletterImageRouteImport } from './routes/api/public/newsletter-image'
import { Route as ApiPublicNewsletterImageUploadRouteImport } from './routes/api/public/newsletter-image-upload'
import { Route as AppRsIndexRouteImport } from './routes/app.rs.index'
import { Route as AppRsIdRouteImport } from './routes/app.rs.$id'
import { Route as RsVagaJobIdRouteImport } from './routes/rs.vaga.$jobId'
import { Route as AppRsVagaJobIdRouteImport } from './routes/app.rs.vaga.$jobId'
import { Route as AppRsVagaNovaRouteImport } from './routes/app.rs.vaga.nova'
import { Route as AppRsVagaJobIdNovoRouteImport } from './routes/app.rs.vaga.$jobId_.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RhNewsRoute = RhNewsRouteImport.update({
  id: '/rh-news',
  path: '/rh-news',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const RsIndexRoute = RsIndexRouteImport.update({
  id: '/rs/',
  path: '/rs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RsIdRoute = RsIdRouteImport.update({
  id: '/rs/$id',
  path: '/rs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RsPainelRoute = RsPainelRouteImport.update({
  id: '/rs/painel',
  path: '/rs/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterImageRoute =
  ApiPublicNewsletterImageRouteImport.update({
    id: '/api/public/newsletter-image',
    path: '/api/public/newsletter-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsletterImageUploadRoute =
  ApiPublicNewsletterImageUploadRouteImport.update({
    id: '/api/public/newsletter-image-upload',
    path: '/api/public/newsletter-image-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppRsIndexRoute = AppRsIndexRouteImport.update({
  id: '/app/rs/',
  path: '/app/rs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRsIdRoute = AppRsIdRouteImport.update({
  id: '/app/rs/$id',
  path: '/app/rs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RsVagaJobIdRoute = RsVagaJobIdRouteImport.update({
  id: '/rs/vaga/$jobId',
  path: '/rs/vaga/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRsVagaJobIdRoute = AppRsVagaJobIdRouteImport.update({
  id: '/app/rs/vaga/$jobId',
  path: '/app/rs/vaga/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRsVagaNovaRoute = AppRsVagaNovaRouteImport.update({
  id: '/app/rs/vaga/nova',
  path: '/app/rs/vaga/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRsVagaJobIdNovoRoute = AppRsVagaJobIdNovoRouteImport.update({
  id: '/app/rs/vaga/$jobId_/novo',
  path: '/app/rs/vaga/$jobId/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rh-news': typeof RhNewsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/rs/$id': typeof RsIdRoute
  '/rs/painel': typeof RsPainelRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/rs/': typeof RsIndexRoute
  '/api/public/newsletter-image': typeof ApiPublicNewsletterImageRoute
  '/api/public/newsletter-image-upload': typeof ApiPublicNewsletterImageUploadRoute
  '/app/rs/$id': typeof AppRsIdRoute
  '/rs/vaga/$jobId': typeof RsVagaJobIdRoute
  '/app/rs/': typeof AppRsIndexRoute
  '/app/rs/vaga/$jobId': typeof AppRsVagaJobIdRoute
  '/app/rs/vaga/nova': typeof AppRsVagaNovaRoute
  '/app/rs/vaga/$jobId/novo': typeof AppRsVagaJobIdNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rh-news': typeof RhNewsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/rs/$id': typeof RsIdRoute
  '/rs/painel': typeof RsPainelRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/rs': typeof RsIndexRoute
  '/api/public/newsletter-image': typeof ApiPublicNewsletterImageRoute
  '/api/public/newsletter-image-upload': typeof ApiPublicNewsletterImageUploadRoute
  '/app/rs/$id': typeof AppRsIdRoute
  '/rs/vaga/$jobId': typeof RsVagaJobIdRoute
  '/app/rs': typeof AppRsIndexRoute
  '/app/rs/vaga/$jobId': typeof AppRsVagaJobIdRoute
  '/app/rs/vaga/nova': typeof AppRsVagaNovaRoute
  '/app/rs/vaga/$jobId/novo': typeof AppRsVagaJobIdNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rh-news': typeof RhNewsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/rs/$id': typeof RsIdRoute
  '/rs/painel': typeof RsPainelRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/rs/': typeof RsIndexRoute
  '/api/public/newsletter-image': typeof ApiPublicNewsletterImageRoute
  '/api/public/newsletter-image-upload': typeof ApiPublicNewsletterImageUploadRoute
  '/app/rs/$id': typeof AppRsIdRoute
  '/rs/vaga/$jobId': typeof RsVagaJobIdRoute
  '/app/rs/': typeof AppRsIndexRoute
  '/app/rs/vaga/$jobId': typeof AppRsVagaJobIdRoute
  '/app/rs/vaga/nova': typeof AppRsVagaNovaRoute
  '/app/rs/vaga/$jobId_/novo': typeof AppRsVagaJobIdNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rh-news'
    | '/admin/dashboard'
    | '/rs/$id'
    | '/rs/painel'
    | '/admin/'
    | '/app/'
    | '/rs/'
    | '/api/public/newsletter-image'
    | '/api/public/newsletter-image-upload'
    | '/app/rs/$id'
    | '/rs/vaga/$jobId'
    | '/app/rs/'
    | '/app/rs/vaga/$jobId'
    | '/app/rs/vaga/nova'
    | '/app/rs/vaga/$jobId/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rh-news'
    | '/admin/dashboard'
    | '/rs/$id'
    | '/rs/painel'
    | '/admin'
    | '/app'
    | '/rs'
    | '/api/public/newsletter-image'
    | '/api/public/newsletter-image-upload'
    | '/app/rs/$id'
    | '/rs/vaga/$jobId'
    | '/app/rs'
    | '/app/rs/vaga/$jobId'
    | '/app/rs/vaga/nova'
    | '/app/rs/vaga/$jobId/novo'
  id:
    | '__root__'
    | '/'
    | '/rh-news'
    | '/admin/dashboard'
    | '/rs/$id'
    | '/rs/painel'
    | '/admin/'
    | '/app/'
    | '/rs/'
    | '/api/public/newsletter-image'
    | '/api/public/newsletter-image-upload'
    | '/app/rs/$id'
    | '/rs/vaga/$jobId'
    | '/app/rs/'
    | '/app/rs/vaga/$jobId'
    | '/app/rs/vaga/nova'
    | '/app/rs/vaga/$jobId_/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RhNewsRoute: typeof RhNewsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  RsIdRoute: typeof RsIdRoute
  RsPainelRoute: typeof RsPainelRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
  RsIndexRoute: typeof RsIndexRoute
  ApiPublicNewsletterImageRoute: typeof ApiPublicNewsletterImageRoute
  ApiPublicNewsletterImageUploadRoute: typeof ApiPublicNewsletterImageUploadRoute
  AppRsIdRoute: typeof AppRsIdRoute
  RsVagaJobIdRoute: typeof RsVagaJobIdRoute
  AppRsIndexRoute: typeof AppRsIndexRoute
  AppRsVagaJobIdRoute: typeof AppRsVagaJobIdRoute
  AppRsVagaNovaRoute: typeof AppRsVagaNovaRoute
  AppRsVagaJobIdNovoRoute: typeof AppRsVagaJobIdNovoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rh-news': {
      id: '/rh-news'
      path: '/rh-news'
      fullPath: '/rh-news'
      preLoaderRoute: typeof RhNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rs/': {
      id: '/rs/'
      path: '/rs'
      fullPath: '/rs/'
      preLoaderRoute: typeof RsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rs/$id': {
      id: '/rs/$id'
      path: '/rs/$id'
      fullPath: '/rs/$id'
      preLoaderRoute: typeof RsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rs/painel': {
      id: '/rs/painel'
      path: '/rs/painel'
      fullPath: '/rs/painel'
      preLoaderRoute: typeof RsPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter-image': {
      id: '/api/public/newsletter-image'
      path: '/api/public/newsletter-image'
      fullPath: '/api/public/newsletter-image'
      preLoaderRoute: typeof ApiPublicNewsletterImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter-image-upload': {
      id: '/api/public/newsletter-image-upload'
      path: '/api/public/newsletter-image-upload'
      fullPath: '/api/public/newsletter-image-upload'
      preLoaderRoute: typeof ApiPublicNewsletterImageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rs/': {
      id: '/app/rs/'
      path: '/app/rs'
      fullPath: '/app/rs/'
      preLoaderRoute: typeof AppRsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rs/$id': {
      id: '/app/rs/$id'
      path: '/app/rs/$id'
      fullPath: '/app/rs/$id'
      preLoaderRoute: typeof AppRsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rs/vaga/$jobId': {
      id: '/rs/vaga/$jobId'
      path: '/rs/vaga/$jobId'
      fullPath: '/rs/vaga/$jobId'
      preLoaderRoute: typeof RsVagaJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rs/vaga/$jobId': {
      id: '/app/rs/vaga/$jobId'
      path: '/app/rs/vaga/$jobId'
      fullPath: '/app/rs/vaga/$jobId'
      preLoaderRoute: typeof AppRsVagaJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rs/vaga/nova': {
      id: '/app/rs/vaga/nova'
      path: '/app/rs/vaga/nova'
      fullPath: '/app/rs/vaga/nova'
      preLoaderRoute: typeof AppRsVagaNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rs/vaga/$jobId_/novo': {
      id: '/app/rs/vaga/$jobId_/novo'
      path: '/app/rs/vaga/$jobId/novo'
      fullPath: '/app/rs/vaga/$jobId/novo'
      preLoaderRoute: typeof AppRsVagaJobIdNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RhNewsRoute: RhNewsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  RsIdRoute: RsIdRoute,
  RsPainelRoute: RsPainelRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
  RsIndexRoute: RsIndexRoute,
  ApiPublicNewsletterImageRoute: ApiPublicNewsletterImageRoute,
  ApiPublicNewsletterImageUploadRoute: ApiPublicNewsletterImageUploadRoute,
  AppRsIdRoute: AppRsIdRoute,
  RsVagaJobIdRoute: RsVagaJobIdRoute,
  AppRsIndexRoute: AppRsIndexRoute,
  AppRsVagaJobIdRoute: AppRsVagaJobIdRoute,
  AppRsVagaNovaRoute: AppRsVagaNovaRoute,
  AppRsVagaJobIdNovoRoute: AppRsVagaJobIdNovoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
